### PR TITLE
Obvious Fix - typos in README

### PR DESCRIPTION
**Pull request by AIElemental**
minor typos fix in README

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@AIElemental Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-samples/zero-downtime-deployment&pullRequestId=4)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud-samples/zero-downtime-deployment&pullRequestId=4) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by AIElemental** [comment]
@marcingrzejszczak Hi, could you please merge typos fixes

**Comment by marcingrzejszczak** [comment]
Yes, after you sign the CLA

**Comment by pivotal-issuemaster** [comment]
@AIElemental Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-samples/zero-downtime-deployment&pullRequestId=4)!

**Comment by AIElemental** [comment]
done!

**Comment by marcingrzejszczak** [comment]
Congrats!!!

**Comment by AIElemental** [comment]
Hi, @marcingrzejszczak , why did you close the request without merging? Do you disagree with them?

**Comment by marcingrzejszczak** [comment]
@AIElemental I clicked the wrong button ;)

**Pull request merged**
